spring:
  application:
    name: taxibroker
  datasource:
    url: jdbc:mysql://localhost:3306/taxibroker_api?createDatabaseIfNotExist=true
    username: root
    password: wonder4415!
    show-sql: true
  flyway:
    enabled: true